adding ICSP config utilities
RedHatQE/openshift-python-utilities pull request #192
Opened 2023-05-04 14:11 UTC by omrirh

Adding support for ImageContentSourcePolicy creation

2023-05-04 15:02 UTC, myakove requested changes

2023-05-04 15:02 UTC, myakove commented on ocp_utilities/infra.py
> +    rc, _, _ = run_command(
```
assert run_command(
        command=shlex.split(base_command),
        verify_stderr=False,
    )[0]
```

2023-05-07 05:56 UTC, omrirh commented on ocp_utilities/infra.py
> +    rc, _, _ = run_command(
done

2023-05-07 07:41 UTC, myakove submitted a review, later dismissed

2023-05-07 09:20 UTC, rnetser approved these changes

2023-05-07 14:10 UTC, omrirh commented
/verified

2023-05-08 07:44 UTC, myakove approved these changes

2023-05-08 07:44 UTC, myakove commented
depends on https://github.com/RedHatQE/openshift-python-wrapper/pull/1211

2023-05-08 07:50 UTC, rnetser commented
@omrirh this PR requires https://github.com/RedHatQE/openshift-python-wrapper/pull/1211 to be merged and cherrypicked; marking this PR as `verified` (and thus leading to its merge) will lead to broken code. Please remove.

2023-05-08 08:01 UTC, omrirh commented
/~verified

2023-05-08 11:30 UTC, omrirh commented
/verified

2023-05-08 11:43 UTC, rnetser approved these changes

2023-05-08 11:43 UTC, merged