A little change with checking for firing alert
RedHatQE/openshift-python-utilities pull request #236
Opened 2023-06-20 16:56 UTC by OhadRevah

##### Short description:
Changed the function get_firing_alerts in monitor.py, Added the option to check for alerts with other states than only firing, with that the name of the function chanaged.

According to it I've changed the wait_for_firing_alert_sampler so it will pass the state argument through the sampler and edited the same of it.

##### More details:

##### What this PR does / why we need it:
I've been testing alerts, and I needed a to check alerts that have 
a long evaluation time, in this cases we check for pending state, so I tried to add
that option and it was very handy while working with alerts.

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2023-06-20 17:01 UTC, omrirh commented on ocp_utilities/monitoring.py
> +        get all the alerts from list of active alerts according the state
```suggestion
        get all the alerts from list of active alerts according to the state
```

2023-06-20 17:13 UTC, omrirh approved these changes

2023-06-20 17:15 UTC, myakove requested changes
Please change the pr title to something more meaningful

2023-06-21 13:23 UTC, myakove requested changes

2023-06-21 13:23 UTC, myakove commented on ocp_utilities/monitoring.py
> -    def get_firing_alerts(self, alert_name):
You renamed the function, this is a breaking change
Please make sure to mention it in the pr title

2023-06-21 17:45 UTC, rnetser approved these changes

2023-06-22 06:55 UTC, omrirh approved these changes

2023-06-22 08:55 UTC, myakove commented
/lgtm

2023-06-22 17:22 UTC, jpeimer requested changes
Maybe it would be better to add new functions without removing the old ones? 
And add a deprecation warning for the old ones?

2023-06-23 10:07 UTC, myakove commented
> Maybe it would be better to add new functions without removing the old ones? And add a deprecation warning for the old ones?

Great idea @jpeimer, 
@OhadRevah Please implement it.

2023-06-27 14:38 UTC, omrirh approved these changes

2023-06-27 14:56 UTC, jpeimer requested changes
Thanks Ohad,

A couple of comments + 
Please update the commit message

2023-06-27 14:56 UTC, jpeimer commented on ocp_utilities/monitoring.py
> +    def get_alerts_by_state(self, alert_name, state="firing"):
Please reuse this function in **get_firing_alerts**

2023-06-27 14:56 UTC, jpeimer commented on ocp_utilities/monitoring.py
> +    def wait_for_alert_by_state_sampler(
Please reuse this function in **wait_for_firing_alert_sampler**

2023-06-27 15:54 UTC, jpeimer commented
/lgtm

2023-06-28 10:09 UTC, omrirh approved these changes

2023-06-28 12:03 UTC, myakove requested changes

2023-06-28 12:03 UTC, myakove commented on ocp_utilities/monitoring.py
> +        except TimeoutExpiredError:
Please remove try:excpect
No need to do it only for the error log, You will have the info from `TimeoutExpiredError` error

2023-06-28 14:42 UTC, omrirh approved these changes

2023-06-28 14:59 UTC, jpeimer approved these changes

2023-06-29 08:37 UTC, myakove approved these changes

2023-06-29 11:57 UTC, rnetser approved these changes

2023-07-04 11:11 UTC, OhadRevah commented on ocp_utilities/monitoring.py
>          """
We discussed about it earlier, I did it at first place but it decided that these functions will be an extension, you can see the previous comments from Meni  and Jenia.

2023-07-04 11:11 UTC, OhadRevah commented on ocp_utilities/monitoring.py
>      def wait_for_firing_alert_sampler(self, alert_name, timeout=TIMEOUT_10MIN):
Same as my last comment.

2023-07-04 11:27 UTC, oharan2 approved these changes

2023-07-04 12:25 UTC, OhadRevah commented
/verified

2023-07-04 12:26 UTC, merged

2023-07-04 12:46 UTC, OhadRevah commented
/cherry-pick v4.14

2023-08-03 14:56 UTC, OhadRevah commented
/cherry-pick v4.14