Added vault_utils.py
RedHatQE/openshift-python-utilities pull request #86
Opened 2023-01-15 10:47 UTC by oharan2

##### Short description: _Added the 'get_vault_config' function for general usage_

##### More details: _+Updated requirements file_

##### What this PR does / why we need it: _Creates a vault client and read data (generic implementation, need to provide api url, secred id and other parameters)_

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2023-01-15 10:47 UTC, oharan2 commented
!verified

2023-01-15 10:54 UTC, rnetser requested changes

2023-01-15 10:54 UTC, rnetser commented on ocp_utilities/vault_utils.py
> +        data_path (str): path within vault to read from 'apps/data/..
`'apps/data/..` - is it always this path? if not, please remove

2023-01-15 10:54 UTC, rnetser commented on ocp_utilities/vault_utils.py
> +        role_id (str): for example: 'mps-qe'
please update to explain what this is (based on vault) and remove any internal examples. this repo is public

2023-01-15 10:54 UTC, rnetser commented on ocp_utilities/vault_utils.py
> +        secret_id (str): could be exported env variable
please update the description to explain what is the secret id; should not include `could be exported env variable`; this is not relevant to this function

2023-01-15 10:54 UTC, rnetser commented on ocp_utilities/vault_utils.py
> +        LOGGER.error("Failed to connect to vault.")
please add exception text fo the log

2023-01-15 15:11 UTC, myakove commented
I don't think this belongs here, this is OpenShift utilities repo

2023-01-16 09:04 UTC, rnetser commented
@oharan2 as we no longer need this in multiple place, please move to the `integrations` repo

2023-01-16 19:36 UTC, closed without merging